### ISSUE TITLE
installer does not work on win 10 x64

### ISSUE THREAD

**Issue by hgy59** [autarchprinceps/MultiCastor#72]
Tried to install MultiCastor with the downloaded installer `MultiCastor_install.jar`

After selecting both packages and pressin "next", the wizard shows an empty page. With next the installation hangs an can only terminated with close window [x].

When starting the installer like this:
`java -verbose:class -esa -jar .\MultiCastor_install.jar`

it shows an exeption while the empty wizard page is shown:
```
...
[Loaded java.lang.ClassLoaderHelper from C:\Program Files\Java\jre1.8.0_181\lib\rt.jar]
could not create shortcut instance
[Loaded java.lang.Throwable$PrintStreamOrWriter from C:\Program Files\Java\jre1.8.0_181\lib\rt.jar]
[Loaded java.lang.Throwable$WrappedPrintStream from C:\Program Files\Java\jre1.8.0_181\lib\rt.jar]
java.lang.Exception: error loading library
java.lang.Exception: can't locate library
        at com.izforge.izpack.util.Librarian.loadArchSpecificLibrary(Unknown Source)
        at com.izforge.izpack.util.Librarian.loadLibrary(Unknown Source)
        at com.izforge.izpack.util.os.ShellLink.initialize(Unknown Source)
        at com.izforge.izpack.util.os.ShellLink.<init>(Unknown Source)
        at com.izforge.izpack.util.os.Win_Shortcut.initialize(Unknown Source)
        at com.izforge.izpack.panels.ShortcutPanel.panelActivate(Unknown Source)
        at com.izforge.izpack.installer.InstallerFrame.switchPanel(Unknown Source)
        at com.izforge.izpack.installer.InstallerFrame.navigateNext(Unknown Source)
        at com.izforge.izpack.installer.InstallerFrame.navigateNext(Unknown Source)
        at com.izforge.izpack.installer.InstallerFrame$NavigationHandler.navigate(Unknown Source)
        at com.izforge.izpack.installer.InstallerFrame$NavigationHandler.access$100(Unknown Source)
        at com.izforge.izpack.installer.InstallerFrame$NavigationHandler$1.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[Loaded com.sun.org.apache.xerces.internal.dom.DeepNodeListImpl from C:\Program Files\Java\jre1.8.0_181\lib\rt.jar]
[Loaded com.izforge.izpack.panels.ShortcutData from file:/E:/Streaming/MultiCastor_install.jar]
[Loaded com.izforge.izpack.util.xml.XMLHelper from file:/E:/Streaming/MultiCastor_install.jar]
java.lang.NullPointerException
        at com.izforge.izpack.util.os.Win_Shortcut.getProgramsFolder(Unknown Source)
        at com.izforge.izpack.panels.ShortcutPanel.getProgramsFolder(Unknown Source)
        at com.izforge.izpack.panels.ShortcutPanel.panelActivate(Unknown Source)
        at com.izforge.izpack.installer.InstallerFrame.switchPanel(Unknown Source)
        at com.izforge.izpack.installer.InstallerFrame.navigateNext(Unknown Source)
        at com.izforge.izpack.installer.InstallerFrame.navigateNext(Unknown Source)
        at com.izforge.izpack.installer.InstallerFrame$NavigationHandler.navigate(Unknown Source)
        at com.izforge.izpack.installer.InstallerFrame$NavigationHandler.access$100(Unknown Source)
        at com.izforge.izpack.installer.InstallerFrame$NavigationHandler$1.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

Looks like the `com.izforge.izpack.util` library is missing in the installer.

Running with java
```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

on Windows 10 x64:
`Microsoft Windows [Version 10.0.17134.165]`
Language is German (Switzerland)

any idea whats goin wrong here?

**Comment by hgy59** [comment]
Tried on another windows pc
same java version and same windows version.
The installer works as expected. The page that is empty on the other system is the "Setup Shortcuts" configuration.

So I generated compared the log files and found the only difference: on the working system the 32-bit version of Java was installed.
So I installed the 32-bit Java on my first system (in parallel to the 64-bit version).
when explicitly calling the installer with 32-bit Java everything works as expected.

This command line works:
`'C:\Program Files (x86)\Java\jdk1.8.0_161\bin\java.exe' -jar .\MultiCastor_install.jar`

For a Java noob like me (java is an island, isn't it?) it would be usefull to have a hint on the download page, telling the need of 32-bit java on Windows x64 systems.

Thanks for this tool.
